//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID { get; set; }
        public string AppCode { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public int ParameterID { get; set; }
        public int ClientID { get; set; }
        public int PriorityLevelID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Parameter Parameter { get; set; }
        public virtual PriorityLevel PriorityLevel { get; set; }
        public virtual aStatus aStatus { get; set; }
        public virtual aType aType { get; set; }
    }
}
