//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authoriz
    {
        public Authoriz()
        {
            this.Agents = new HashSet<Agents>();
            this.Clients = new HashSet<Clients>();
        }
    
        public int ID { get; set; }
        public string UserLogin { get; set; }
        public string hashPassword { get; set; }
    
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
