//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Applications = new HashSet<Applications>();
            this.Deals = new HashSet<Deals>();
            this.EstateObject = new HashSet<EstateObject>();
        }
    
        public int ID { get; set; }
        public string Surname { get; set; }
        public string cName { get; set; }
        public string Patronymic { get; set; }
        public int AuthoID { get; set; }
        public int PersonalDataID { get; set; }
    
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual Authoriz Authoriz { get; set; }
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual ICollection<EstateObject> EstateObject { get; set; }
        public virtual PersonalData PersonalData { get; set; }
    }
}
