//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ID { get; set; }
        public string ContractCode { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public string ContrDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime SignDate { get; set; }
    
        public virtual cStatus cStatus { get; set; }
        public virtual cType cType { get; set; }
        public virtual Deals Deals { get; set; }
    }
}
