//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cStatus
    {
        public cStatus()
        {
            this.Contracts = new HashSet<Contracts>();
        }
    
        public int ID { get; set; }
        public string StatusType { get; set; }
    
        public virtual ICollection<Contracts> Contracts { get; set; }
    }
}
