//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int ID { get; set; }
        public string DealCode { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime SignDate { get; set; }
        public int EstateObjectID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Contracts Contracts { get; set; }
        public virtual EstateObject EstateObject { get; set; }
        public virtual dStatus dStatus { get; set; }
        public virtual dType dType { get; set; }
    }
}
