//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diploma
    {
        public int ID { get; set; }
        public int PersonID { get; set; }
        public int PlaceOfStudyID { get; set; }
        public int DegreeID { get; set; }
        public int SpecialityID { get; set; }
        public int StudyForm { get; set; }
        public int PeriodID { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual EducPeriod EducPeriod { get; set; }
        public virtual PersonalData PersonalData { get; set; }
        public virtual PlaceOfStudy PlaceOfStudy { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual StudyForm StudyForm1 { get; set; }
    }
}
