//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dType
    {
        public dType()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int ID { get; set; }
        public string DealType { get; set; }
    
        public virtual ICollection<Deals> Deals { get; set; }
    }
}
