//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eStatus
    {
        public eStatus()
        {
            this.EstateObject = new HashSet<EstateObject>();
        }
    
        public int ID { get; set; }
        public string StatusType { get; set; }
    
        public virtual ICollection<EstateObject> EstateObject { get; set; }
    }
}
