//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstateObject
    {
        public EstateObject()
        {
            this.Deals = new HashSet<Deals>();
        }
    
        public int ID { get; set; }
        public string eoAddress { get; set; }
        public int TypeID { get; set; }
        public int RoomCount { get; set; }
        public decimal Area { get; set; }
        public Nullable<int> Floors { get; set; }
        public int StatusID { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> HasBalcony { get; set; }
        public Nullable<bool> HasParking { get; set; }
        public Nullable<bool> HasFurniture { get; set; }
        public Nullable<bool> HasAppliances { get; set; }
        public int OwnerID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Deals> Deals { get; set; }
        public virtual eStatus eStatus { get; set; }
        public virtual eType eType { get; set; }
        public virtual TechnicalConclusion TechnicalConclusion { get; set; }
    }
}
