//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int ID { get; set; }
        public decimal MaxPrice { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxArea { get; set; }
        public decimal MinArea { get; set; }
        public int MaxRooms { get; set; }
        public int MinRooms { get; set; }
        public Nullable<bool> hasBalcony { get; set; }
        public Nullable<bool> hasFurniture { get; set; }
        public Nullable<bool> hasAppliances { get; set; }
        public Nullable<int> RecFloor { get; set; }
    
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
