//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace практическая_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalConclusion
    {
        public int ID { get; set; }
        public int TechnicalConditionID { get; set; }
        public Nullable<bool> HasDeffects { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsToExploitation { get; set; }
    
        public virtual EstateObject EstateObject { get; set; }
        public virtual TechnicalCondition TechnicalCondition { get; set; }
    }
}
